# -*- coding: utf-8 -*-
"""Районы Бали: уникальный контент для страниц /areas/<slug>/ (EN + RU).
Факты общего характера — перед запуском сверить с реальной зоной выезда нянь и временем дороги."""

AREAS = [
 dict(slug="sanur", en="Sanur", ru="Санур", ru_in="в Сануре",
  en_lead="Calm, reef-protected water and a flat beachfront path make Sanur the easiest part of Bali for babies and toddlers.",
  ru_lead="Спокойная вода за рифом и ровная набережная делают Санур самым удобным районом Бали для малышей.",
  en_txt=[("Why families choose Sanur","The reef keeps waves small, so little ones can paddle safely around high tide. The 5 km beach path is stroller-friendly, and most hotels, cafes and playgrounds are within walking distance."),
      ("What our nannies do here","Morning beach time and sandcastles, pool sessions at your hotel, naps while you take a SUP or snorkel trip, and evenings in so you can try a sunset dinner."),
      ("Good to know","At low tide the water drops far out over the reef — plan swims around high tide. Fast boats to Nusa Lembongan and Nusa Penida leave from Sanur beach.")],
  ru_txt=[("Почему семьи выбирают Санур","Риф гасит волны, поэтому малыши могут плескаться у берега в прилив. Набережная длиной около 5 км удобна для колясок, а отели, кафе и детские площадки — в пешей доступности."),
      ("Чем занимаются наши няни","Утро на пляже и замки из песка, бассейн в отеле, дневной сон, пока вы на сапе или снорклинге, и вечер с детьми, пока вы ужинаете на закате."),
      ("Полезно знать","В отлив вода уходит далеко за риф — купайтесь в прилив. С пляжа Санура уходят скоростные лодки на Нуса Лембонган и Нуса Пениду.")]),
 dict(slug="canggu", en="Canggu", ru="Чангу", ru_in="в Чангу",
  en_lead="Surf, cafes and villas with private pools — Canggu suits families who want an active, social Bali stay.",
  ru_lead="Сёрф, кафе и виллы с бассейнами — Чангу для семей, которым нужен активный и живой Бали.",
  en_txt=[("Families in Canggu","Most families stay in villas in Berawa, Pererenan or Batu Bolong. Days revolve around the villa pool, beach cafes with play areas and surf lessons for older kids."),
      ("What our nannies do here","Pool supervision at your villa, playdates at family cafes, nap routines while you surf or work from a coworking space, and evening babysitting for dinners out."),
      ("Good to know","Canggu beaches are black sand with strong waves and currents — children should swim only between flags or in the pool. Traffic is heavy at peak hours, so we book nannies who live nearby.")],
  ru_txt=[("Семьи в Чангу","Обычно семьи живут на виллах в Бераве, Перерэнане или Бату Болонге. День строится вокруг бассейна, пляжных кафе с детскими зонами и уроков сёрфинга для детей постарше."),
      ("Чем занимаются наши няни","Присмотр у бассейна на вилле, прогулки в семейные кафе, дневной сон, пока вы на сёрфе или в коворкинге, и вечерние выходы родителей."),
      ("Полезно знать","Пляжи Чангу — чёрный песок, сильные волны и течения: детям купаться только между флагами или в бассейне. В часы пик пробки, поэтому подбираем нянь, живущих рядом.")]),
 dict(slug="seminyak", en="Seminyak", ru="Семиньяк", ru_in="в Семиньяке",
  en_lead="Boutique villas, beach clubs and restaurants — Seminyak is Bali's stylish base for families who like to go out.",
  ru_lead="Бутик-виллы, бич-клабы и рестораны — Семиньяк для семей, которые любят выходить вечером.",
  en_txt=[("Families in Seminyak","Private-pool villas and beachfront resorts sit close to some of Bali's best restaurants. Families split days between the villa, the beach and shopping streets."),
      ("What our nannies do here","Evening babysitting while you dine or visit a beach club, pool and play time at the villa, and help with bedtime routines."),
      ("Good to know","The surf is strong along Seminyak beach — supervision near the water is essential. Many beach clubs are adults-focused in the evening, so a sitter at the villa is the easy option.")],
  ru_txt=[("Семьи в Семиньяке","Виллы с собственным бассейном и отели на первой линии рядом с лучшими ресторанами острова. День делится между виллой, пляжем и магазинами."),
      ("Чем занимаются наши няни","Вечерний присмотр, пока вы в ресторане или бич-клабе, игры и бассейн на вилле, укладывание спать."),
      ("Полезно знать","Волны на пляже Семиньяка сильные — у воды нужен постоянный присмотр. Вечером многие бич-клабы рассчитаны на взрослых, поэтому удобнее оставить детей с няней на вилле.")]),
 dict(slug="kuta-legian", en="Kuta & Legian", ru="Кута и Легиан", ru_in="в Куте и Легиане",
  en_lead="Close to the airport and Waterbom, Kuta and Legian are an easy first stop for families arriving in Bali.",
  ru_lead="Рядом аэропорт и аквапарк Waterbom — Кута и Легиан удобны для первых дней на Бали.",
  en_txt=[("Families in Kuta & Legian","Big hotels with kids' pools, shopping malls and Waterbom waterpark make this area practical, especially after a long flight."),
      ("What our nannies do here","Jet-lag nights with a night nanny, hotel pool afternoons, and a day at Waterbom with an extra pair of hands."),
      ("Good to know","Kuta beach has beginner surf schools but also rips — swim between the flags. Streets are busy, so we plan outings around short walks and taxis.")],
  ru_txt=[("Семьи в Куте и Легиане","Большие отели с детскими бассейнами, торговые центры и аквапарк Waterbom — практичный вариант, особенно после долгого перелёта."),
      ("Чем занимаются наши няни","Ночная няня в дни джетлага, бассейн в отеле, день в Waterbom с лишней парой рук."),
      ("Полезно знать","В Куте есть школы сёрфинга для новичков, но есть и отбойные течения — купайтесь между флагами. Улицы оживлённые, поэтому прогулки короткие, остальное на такси.")]),
 dict(slug="ubud", en="Ubud", ru="Убуд", ru_in="в Убуде",
  en_lead="Rice terraces, jungle villas and cooler air — Ubud is Bali's cultural heart and a gentle place for kids.",
  ru_lead="Рисовые террасы, виллы в джунглях и мягкий климат — Убуд, культурное сердце Бали.",
  en_txt=[("Families in Ubud","Jungle villas with pools, craft workshops, dance shows and rice-field walks. There's no beach, but the climate is milder than on the coast."),
      ("What our nannies do here","Villa days with pool and nature play, company on rice-field walks, and babysitting while you take a yoga class or a cooking class."),
      ("Good to know","Many villas have steep steps and unfenced pools — tell us about the layout so we can plan safety. Keep children away from monkeys at Monkey Forest and temples.")],
  ru_txt=[("Семьи в Убуде","Виллы в джунглях с бассейнами, мастер-классы, танцевальные шоу и прогулки по рисовым полям. Пляжа нет, зато климат мягче, чем на побережье."),
      ("Чем занимаются наши няни","Дни на вилле с бассейном и играми на природе, прогулки по рисовым полям, присмотр, пока вы на йоге или кулинарном классе."),
      ("Полезно знать","На многих виллах крутые лестницы и бассейны без ограждения — расскажите о планировке, чтобы мы продумали безопасность. Держите детей подальше от обезьян в Monkey Forest и у храмов.")]),
 dict(slug="uluwatu", en="Uluwatu", ru="Улувату", ru_in="в Улувату",
  en_lead="Clifftop resorts, famous sunsets and hidden beaches — Uluwatu is Bali at its most dramatic.",
  ru_lead="Отели на скалах, знаменитые закаты и скрытые пляжи — самый живописный Бали.",
  en_txt=[("Families in Uluwatu","Families usually stay in clifftop resorts or villas with big pools. Beaches like Padang Padang and Melasti are beautiful but reached by stairs or steep roads."),
      ("What our nannies do here","Pool supervision at your villa, beach time at calmer spots at low swell, and evening babysitting so you can watch the Kecak dance or a clifftop sunset."),
      ("Good to know","Many beaches are for experienced surfers — choose calm days and stay close. Monkeys at Uluwatu Temple grab belongings; small children are safer in a carrier there.")],
  ru_txt=[("Семьи в Улувату","Обычно семьи живут в отелях на скалах или виллах с большими бассейнами. Пляжи вроде Паданг-Паданг и Меласти красивые, но к ним ведут лестницы или крутые дороги."),
      ("Чем занимаются наши няни","Присмотр у бассейна, пляж в дни без волн, вечерний присмотр, пока вы на танце кечак или закате."),
      ("Полезно знать","Многие пляжи — для опытных сёрферов: выбирайте спокойные дни. Обезьяны у храма Улувату хватают вещи; малышей там лучше носить в переноске.")]),
 dict(slug="jimbaran", en="Jimbaran", ru="Джимбаран", ru_in="в Джимбаране",
  en_lead="A wide, calm bay with seafood dinners on the sand — and just 15 minutes from the airport.",
  ru_lead="Широкая спокойная бухта, ужины из морепродуктов на песке и 15 минут до аэропорта.",
  en_txt=[("Families in Jimbaran","The bay is gentler than Bali's west coast, and large resorts have kids' clubs and shallow pools. Sunset seafood dinners on the beach are a family tradition."),
      ("What our nannies do here","Beach mornings, resort pool time, and an evening sitter so parents can enjoy a quiet dinner."),
      ("Good to know","Waves are usually moderate but change with the season — check conditions before swimming. Jimbaran is a convenient base for short stays near the airport.")],
  ru_txt=[("Семьи в Джимбаране","Бухта спокойнее западного побережья, в больших отелях есть детские клубы и мелкие бассейны. Ужин из морепродуктов на закате — семейная традиция."),
      ("Чем занимаются наши няни","Утро на пляже, бассейн в отеле, вечерний присмотр, чтобы родители спокойно поужинали."),
      ("Полезно знать","Волны обычно умеренные, но меняются в зависимости от сезона — проверяйте перед купанием. Удобная база для коротких поездок рядом с аэропортом.")]),
 dict(slug="nusa-dua", en="Nusa Dua", ru="Нуса Дуа", ru_in="в Нуса Дуа",
  en_lead="Manicured resorts, calm reef-sheltered beaches and kids' clubs — Nusa Dua is Bali's classic family resort area.",
  ru_lead="Ухоженные курорты, спокойное море за рифом и детские клубы — классический семейный район Бали.",
  en_txt=[("Families in Nusa Dua","A gated resort enclave with wide beaches, calm water and big hotels built for families. Everything is flat, clean and easy with a stroller."),
      ("What our nannies do here","Private care when the kids' club is full or your child is too young for it, pool and beach time, and evening babysitting in your room."),
      ("Good to know","Hotels have their own policies for external sitters — we coordinate with reception in advance. The Bali Collection area has shops and restaurants within walking distance.")],
  ru_txt=[("Семьи в Нуса Дуа","Закрытая курортная зона с широкими пляжами, спокойной водой и большими отелями для семей. Всё ровное и чистое, удобно с коляской."),
      ("Чем занимаются наши няни","Индивидуальный присмотр, если детский клуб переполнен или ребёнок для него мал, бассейн и пляж, вечерний присмотр в номере."),
      ("Полезно знать","В отелях свои правила для приглашённых нянь — мы заранее согласуем визит с ресепшн. Рядом Bali Collection с магазинами и ресторанами.")]),
 dict(slug="denpasar", en="Denpasar", ru="Денпасар", ru_in="в Денпасаре",
  en_lead="Bali's capital, where many expat and local families live close to international hospitals and schools.",
  ru_lead="Столица Бали, где живут многие семьи экспатов рядом с международными клиниками и школами.",
  en_txt=[("Families in Denpasar","Denpasar is less about holidays and more about everyday life: homes, schools, malls and the island's main hospitals."),
      ("What our nannies do here","Long-term and part-time nannies for resident families, after-school care and help at home."),
      ("Good to know","Traffic can be heavy, so we match families with nannies from the same part of town and agree on fixed hours.")],
  ru_txt=[("Семьи в Денпасаре","Денпасар — не про отпуск, а про повседневную жизнь: дома, школы, торговые центры и главные больницы острова."),
      ("Чем занимаются наши няни","Няни на длительный срок и неполный день для живущих здесь семей, присмотр после школы, помощь по дому."),
      ("Полезно знать","Бывают пробки, поэтому подбираем няню из того же района и договариваемся о фиксированных часах.")]),
]
